name: CYP-multidms
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - pip
  - pip:
    - multidms
  - jupyter
  - notebook
  - numpy
  - pandas
  - seaborn
  - scipy
  - matplotlib 
  - tqdm
